name: Swift

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test-macos:
        runs-on: macos-13
        env:
            DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: swift build -v
            - name: Test
              run: swift test -v
    test-linux:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                swift: ["6.0"]
        container: swift:${{ matrix.swift }}
        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: swift build
            - name: Run tests
              run: swift test
